apiVersion: v1
kind: ConfigMap
metadata:
    name: adguard-config
    namespace: adguard
    labels:
        app: adguard-home
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: adguard
data:
    AdGuardHome.yaml: |
        http:
          address: 0.0.0.0:80
        dns:
          bind_hosts:
            - 0.0.0.0
          port: 53
          upstream_dns:
            - https://dns10.quad9.net/dns-query
          bootstrap_dns:
            - 9.9.9.10
            - 149.112.112.10
            - 2620:fe::10
            - 2620:fe::fe:10
          protection_enabled: true
          filtering_enabled: true
          safebrowsing_enabled: true
          rewrites:
            - domain: argocd.home
              answer: 10.0.0.240
            - domain: plex.home
              answer: 10.0.0.242
        filtering:
          protection_enabled: true
          filtering_enabled: true
          safebrowsing_enabled: true
          safe_search:
            enabled: true
