apiVersion: apps/v1
kind: Deployment
metadata:
    name: adguard-deployment
    namespace: adguard
spec:
    replicas: 1
    selector:
        matchLabels:
            app: adguard
    template:
        metadata:
            labels:
                app: adguard
        spec:
            initContainers:
                - name: config-init
                  image: busybox:1.35
                  command:
                      - sh
                      - -c
                      - |
                          echo "Applying ConfigMap as source of truth..."
                          cp /tmp/config/AdGuardHome.yaml /opt/adguardhome/work/AdGuardHome.yaml
                          chown 65534:65534 /opt/adguardhome/work/AdGuardHome.yaml
                          chmod 600 /opt/adguardhome/work/AdGuardHome.yaml
                          echo "ConfigMap applied successfully with correct permissions - any web UI changes will be lost on restart"
                  volumeMounts:
                      - name: adguard-data
                        mountPath: /opt/adguardhome/work
                      - name: adguard-config
                        mountPath: /tmp/config
                        readOnly: true
            containers:
                - name: adguard-home
                  image: adguard/adguardhome:latest
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 53 #dns
                        name: dns
                        protocol: UDP
                      - containerPort: 3000 #initial setup
                        name: http-initial
                      - containerPort: 80 #web gui
                        name: http
                        protocol: TCP
                  volumeMounts:
                      - name: adguard-data
                        mountPath: /opt/adguardhome/work
            volumes:
                - name: adguard-data
                  persistentVolumeClaim:
                      claimName: adguard-pvc
                - name: adguard-config
                  configMap:
                      name: adguard-config
