apiVersion: v1
kind: ConfigMap
metadata:
    name: adguard-config
    namespace: adguard
    labels:
        app: adguard-home
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: adguard
data:
    AdGuardHome.yaml: |
        dns:
          protection_enabled: true
          filtering_enabled: true
          safebrowsing_enabled: true
          safesearch_enabled: true
          querylog_enabled: true
          rewrites:
            - domain: argocd.home
              answer: 10.0.0.240
            - domain: plex.home
              answer: 10.0.0.242
