apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-config-pvc
    namespace: adguard
    labels:
        app: adguard-home
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: adguard
    annotations:
        description: "PVC for AdGuard Home configuration files (DNS settings, rewrites, etc.)"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi
