apiVersion: v1
kind: ConfigMap
metadata:
    name: adguard-config
    namespace: adguard
    labels:
        app: adguard-home
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: adguard
data:
    AdGuardHome.yaml: |
        dns:
          rewrites:
            - domain: argocd.home
              answer: 10.0.0.240
            - domain: plex.home
              answer: 10.0.0.242
          protection_enabled: true
          filtering_enabled: true
          safebrowsing_enabled: true
        filtering:
          protection_enabled: true
          filtering_enabled: true
          safebrowsing_enabled: true
          safe_search:
            enabled: true
        querylog:
          enabled: true
          file_enabled: true
          interval: 2160h
          size_memory: 1000
        statistics:
          enabled: true
          interval: 24h
        users:
          - name: admin
            password: $2a$10$ThisisaplaceholderpasswordhashForInitialSetup
        auth_attempts: 5
        block_auth_min: 15
        dns:
          bind_hosts:
            - 0.0.0.0
          port: 53
          upstream_dns:
            - https://dns10.quad9.net/dns-query
          bootstrap_dns:
            - 9.9.9.10
            - 149.112.112.10
            - 2620:fe::10
            - 2620:fe::fe:10
        schema_version: 29
