# Configuration for rm3l AdGuard Home chart
env:
    TZ: "America/Toronto"

services:
    dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.0.241
        externalTrafficPolicy: Local

persistence:
    volumeClaimSpec:
        accessModes:
            - ReadWriteOnce
        storageClassName: longhorn
        resources:
            requests:
                storage: 5Gi

# AdGuard Home configuration
bootstrapConfig:
    dns:
        upstream_dns:
            - 1.1.1.1
            - 8.8.8.8
    rewrites:
        - domain: "argocd.home"
          answer: "10.0.0.240"
        - domain: "plex.home"
          answer: "10.0.0.242"
