persistence:
    config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 2Gi
    data:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 5Gi

service:
    main:
        enabled: true
        primary: true
        type: ClusterIP
        ports:
            main:
                enabled: true
                primary: true
                port: 3000
                protocol: http
                targetPort: 3000
    dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.0.241
        ports:
            dns-tcp:
                enabled: true
                port: 53
                protocol: tcp
                targetPort: 53
    dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.0.241
        ports:
            dns-udp:
                enabled: true
                port: 53
                protocol: udp
                targetPort: 53

env:
    TZ: "America/Toronto"

# AdGuard Home specific configuration through workload environment
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        AGH_CONFIG: |
                            dns:
                                upstream_dns:
                                    - 1.1.1.1
                                    - 8.8.8.8
                                rewrites:
                                    - domain: "argocd.home"
                                      answer: "10.0.0.240"
                                    - domain: "plex.home"  
                                      answer: "10.0.0.242"

ingress:
    main:
        enabled: false

metrics:
    enabled: true
