env:
    TZ: "America/Toronto"

service:
    main:
        ports:
            http:
                port: 3000
    dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.0.241
        ports:
            dns-tcp:
                port: 53
                protocol: TCP
    dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.0.241
        ports:
            dns-udp:
                port: 53
                protocol: UDP

persistence:
    config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 2Gi
    data:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 5Gi

# AdGuard Home configuration
config: |
    dns:
        upstream_dns:
            - 1.1.1.1
            - 8.8.8.8
    rewrites:
        - domain: "argocd.home"
          answer: "10.0.0.240"
        - domain: "plex.home"
          answer: "10.0.0.242"
