apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: home-lab-pool
    namespace: metallb-system
spec:
    addresses:
        - 10.0.0.225-10.0.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: home-lab-l2
    namespace: metallb-system
spec:
    ipAddressPools:
        - home-lab-pool
