apiVersion: v1
kind: Pod
metadata:
    name: test-intel-gpu
    namespace: default
spec:
    restartPolicy: Never
    containers:
        - name: test-gpu
          image: ubuntu:24.04
          command: ["/bin/bash"]
          args:
              - -c
              - |
                  echo "Testing Intel GPU access..."
                  echo "Available GPU devices:"
                  ls -la /dev/dri/ || echo "No /dev/dri devices found"
                  echo ""
                  echo "GPU device permissions:"
                  ls -la /dev/dri/render* 2>/dev/null || echo "No render devices found"
                  echo ""
                  echo "Environment variables:"
                  env | grep -i gpu || echo "No GPU environment variables"
                  echo ""
                  echo "Test completed successfully - GPU device access verified"
                  sleep 30
          resources:
              limits:
                  gpu.intel.com/i915: 1
              requests:
                  gpu.intel.com/i915: 1
          securityContext:
              runAsUser: 0
