apiVersion: v1
kind: Pod
metadata:
    name: fix-inotify-limits
    namespace: default
spec:
    hostNetwork: true
    hostPID: true
    hostIPC: true
    containers:
        - name: fix-inotify
          image: ubuntu:24.04
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 30; done"]
          securityContext:
              privileged: true
          volumeMounts:
              - name: host-sys
                mountPath: /host/sys
              - name: host-proc
                mountPath: /host/proc
              - name: host-etc
                mountPath: /host/etc
    volumes:
        - name: host-sys
          hostPath:
              path: /sys
        - name: host-proc
          hostPath:
              path: /proc
        - name: host-etc
          hostPath:
              path: /etc
    restartPolicy: Never
