apiVersion: v1
kind: ConfigMap
metadata:
  name: bookorbit-config
  namespace: bookorbit
data:
  NODE_ENV: production
  HOST: 0.0.0.0
  PORT: "3000"
  APP_URL: https://bookorbit.nourez.net
  CLIENT_URL: https://bookorbit.nourez.net
  POSTGRES_HOST: bookorbit-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: bookorbit
  POSTGRES_DB: bookorbit
  TZ: America/Toronto
  PUID: "1000"
  PGID: "1000"
  NODE_MAX_OLD_SPACE_SIZE: "2048"
  LIBRARY_BROWSE_ROOT: /books
  BOOK_DOCK_PATH: /data/book-dock
