apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beeper-whatsapp-data
  namespace: beeper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
