apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-kosync-bridge-data
  namespace: abs-kosync-bridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
