apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-config
  namespace: audiobookshelf-hardcover-sync
data:
  # AudioBookShelf service address (in-cluster DNS)
  AUDIOBOOKSHELF_URL: "http://audiobookshelf.audiobookshelf"
  # Sync interval in minutes (default 60)
  SYNC_INTERVAL: "60"
