apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: homebridge-config
    namespace: homebridge
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: longhorn
