apiVersion: v1
kind: Service
metadata:
    name: homebridge
    namespace: homebridge
spec:
    type: LoadBalancer
    loadBalancerIP: 10.0.0.248 # Choose your reserved MetalLB IP (adjust as needed)
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8581
          name: web-ui
    selector:
        app: homebridge
