apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
    name: gpudeviceplugin-sample
    namespace: intel-device-plugins-system
    annotations:
        argocd.argoproj.io/sync-wave: "2"
spec:
    image: intel/intel-gpu-plugin:0.32.1
    logLevel: 2
    enableMonitoring: true
    sharedDevNum: 1
    preferredAllocationPolicy: none
    resourceManager: false
    nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
    tolerations: []
