apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
    name: intel-gpu-plugin
    annotations:
        argocd.argoproj.io/sync-wave: "3"

resources:
    - system-config-daemonset.yaml
    - gpu-device-plugin-values.yaml

namespace: intel-device-plugins-system
