apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
    - namespace.yaml
    - helm-chart-config.yaml
    - transcode-pvc.yaml
    - ingress-route.yaml

commonLabels:
    app: jellyfin
    component: media-server
