apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jellyfin-transcode
    namespace: jellyfin
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 50Gi
