apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: syncthing-config-pvc
    namespace: syncthing
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: longhorn
