apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: lscr.io/linuxserver/calibre-web:0.6.26-ls381
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Toronto
          volumeMounts:
            - name: config
              mountPath: /config
            - name: books
              mountPath: /books
              readOnly: true

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config

        - name: books
          hostPath:
            path: /mnt/media/Books
            type: Directory
