apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crosspoint-sync-data
  namespace: crosspoint-sync
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
