apiVersion: v1
kind: Service
metadata:
    name: samba
    namespace: media-smb
spec:
    type: LoadBalancer
    loadBalancerIP: 10.0.0.244 # Choose your reserved MetalLB IP for media SMB
    ports:
        - port: 445
          protocol: TCP
          targetPort: 445
    selector:
        app: samba
