apiVersion: v1
kind: PersistentVolume
metadata:
    name: media-pv
spec:
    capacity:
        storage: 2500Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /mnt/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: media-pvc
    namespace: media-smb
spec:
    storageClassName: ""
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2500Gi
    volumeName: media-pv
