apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abs-kosync-bridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nourez/klusty-krab-home-lab.git
    targetRevision: HEAD
    path: manifests/abs-kosync-bridge
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: abs-kosync-bridge
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
