apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: adguard
    namespace: argocd
spec:
    project: default
    source:
        repoURL: ghcr.io/gabe565/charts
        chart: adguard-home
        targetRevision: "*"
        helm:
            valueFiles:
                - https://raw.githubusercontent.com/nourez/klusty-krab-home-lab/HEAD/manifests/adguard/values.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: adguard
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
