apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: adguard
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://helm-charts.rm3l.org
        chart: adguard-home
        targetRevision: "*"
        helm:
            valueFiles:
                - https://raw.githubusercontent.com/nourez/klusty-krab-home-lab/78610b0/manifests/adguard/values.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: adguard
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
