apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: adguard
    namespace: argocd
spec:
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
    project: default
    sources:
        - repoURL: ghcr.io/bjw-s/helm
          chart: app-template
          targetRevision: 3.7.3
          helm:
              valueFiles:
                  - $values/manifests/adguard/values.yaml
        - repoURL: git@github.com:nourez/klusty-krab-home-lab.git
          targetRevision: HEAD
          ref: values
    destination:
        server: https://kubernetes.default.svc
        namespace: adguard
