apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: adguard
    namespace: argocd
spec:
    project: default
    sources:
        - repoURL: https://charts.truecharts.org/
          chart: adguard-home
          targetRevision: 11.5.7
          helm:
              valueFiles:
                  - $values/manifests/adguard/values.yaml
        - repoURL: git@github.com:nourez/klusty-krab-home-lab.git
          targetRevision: HEAD
          ref: values
    destination:
        server: https://kubernetes.default.svc
        namespace: adguard
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
