apiVersion: v1
kind: Secret
metadata:
    name: bjw-s-helm-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    name: bjw-s-helm
    type: helm
    url: ghcr.io/bjw-s/helm
    enableOCI: "true"
