apiVersion: v1
kind: Secret
metadata:
    name: ghcr-oci-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    name: ghcr-oci
    type: helm
    url: ghcr.io/gabe565/charts
    enableOCI: "true"
