apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: longhorn2
    namespace: argocd
spec:
    syncPolicy:
        automated:
            # selfHeal disabled - Longhorn modifies CRDs at runtime, selfHeal causes unnecessary sync noise
            prune: true
        syncOptions:
            - CreateNamespace=true
    project: default
    sources:
        - chart: longhorn
          repoURL: https://charts.longhorn.io/
          targetRevision: v1.9.0 # Replace with the Longhorn version you'd like to install or upgrade to
          helm:
              values: |
                  preUpgradeChecker:
                    jobEnabled: false
    destination:
        server: https://kubernetes.default.svc
        namespace: longhorn-storage
