apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: longhorn
    namespace: argocd
spec:
    syncPolicy:
        automated:
            # selfHeal enabled - ignoreDifferences prevents sync noise from runtime CRD modifications
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
    project: default
    sources:
        - chart: longhorn
          repoURL: https://charts.longhorn.io/
          targetRevision: v1.9.0 # Replace with the Longhorn version you'd like to install or upgrade to
          helm:
              values: |
                  preUpgradeChecker:
                    jobEnabled: false
    destination:
        server: https://kubernetes.default.svc
        namespace: longhorn-system
    ignoreDifferences:
        # Ignore differences in Longhorn CRDs that are modified at runtime
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: engineimages.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: engines.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: instancemanagers.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: nodes.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: replicas.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: settings.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: volumes.longhorn.io
          jsonPointers:
              - /spec
              - /metadata/generation
              - /metadata/resourceVersion
              - /metadata/managedFields
              - /status
