apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: placeholder-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: git@github.com:nourez/klusty-krab-home-lab.git
        targetRevision: HEAD
        path: manifests/placeholder
        directory:
            recurse: true
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
