apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: plex
    namespace: argocd
spec:
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
    project: default
    source:
        repoURL: ghcr.io/gabe565/charts
        chart: plex
        targetRevision: 0.5.1
        helm:
            valueFiles:
                - manifests/plex/values.yaml

    destination:
        server: https://kubernetes.default.svc
        namespace: plex
