apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: truecharts
    namespace: argocd
spec:
    project: default
    source:
        repoURL: git@github.com:nourez/klusty-krab-home-lab.git
        targetRevision: HEAD
        path: manifests/truecharts
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
