apiVersion: v1
kind: PersistentVolume
metadata:
    name: roms-pv
spec:
    capacity:
        storage: 900Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /mnt/retrogaming/ROMS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: roms-pvc
    namespace: roms
spec:
    storageClassName: ""
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 900Gi
    volumeName: roms-pv
